WIP: Custom render strategies
livingdocsIO/livingdocs-node-sdk pull request #35
Opened 2021-06-16 14:49 UTC by peyerluk

# Motivation

Allow to render image directives with custom code.

# Changelog

- 🎁 tbd

2021-06-21 08:51 UTC, marcbachmann requested changes
Please announce the node 8 support removal as breaking change.
What's the reason we still support node 12? Maybe only v14 and v16 are needed.

2021-06-21 08:57 UTC, peyerluk commented
> What's the reason we still support node 12?

I used the current images from the framework

2021-06-21 09:22 UTC, merged

2021-06-21 09:25 UTC, marcbachmann commented
Please still announce it as breaking change.

2021-06-22 12:13 UTC, livingdocs-automation commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@livingdocs/node-sdk)
- [GitHub release](https://github.com/livingdocsIO/livingdocs-node-sdk/releases/tag/v1.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: